import pytest
from django.contrib.admin.helpers import ACTION_CHECKBOX_NAME

from admin_actions.actions.queue_celery import QueueCeleryAction
from tests._app.models import AdminActionsTestModel


def test_generated_action_is_registrable(admin, rf, celery_task, admin_user):
    """
    The Admin should have an action calling `queue_action`.
    The action is generated by QueueCeleryAction.
    """

    r = rf.get("/")
    r.user = admin_user

    queue_action = QueueCeleryAction(task=celery_task)
    admin.actions += (queue_action,)

    actions = admin.get_actions(r)
    expected = "tests.conftest.sample_task"  # Generated from the celery_task fixture
    assert expected in actions.keys(), (
        f"Expected action '{expected}' not found in admin actions."
    )
    assert actions[expected][0] is queue_action


def test_generated_action_is_nameable(admin, rf, celery_task, admin_user):
    """QueueCeleryAction should accept a custom name."""
    r = rf.get("/")
    r.user = admin_user

    queue_action = QueueCeleryAction(task=celery_task, name="custom_action_name")
    admin.actions += (queue_action,)

    actions = admin.get_actions(r)
    expected = "custom_action_name"  # Generated from the task
    assert expected in actions.keys(), (
        f"Expected action '{expected}' not found in admin actions."
    )
    assert actions[expected][0] is queue_action


@pytest.mark.django_db
def test_generated_action_is_callable(
    admin,
    mocked_task,
    celery_task,
    model_instance,
    _request,
):
    """The Admin should have a sample_task action"""
    r = _request("post", data={ACTION_CHECKBOX_NAME: [model_instance.pk]})

    queue_action = QueueCeleryAction(task=celery_task)
    queue_action(admin, r, AdminActionsTestModel.objects.filter(pk=model_instance.pk))

    mocked_task.assert_called_once_with(model_instance.pk)


@pytest.mark.django_db
def test_condition_failure_excludes_records(
    admin,
    mocked_task,
    celery_task,
    model_instance,
    _request,
):
    """The Admin should have a sample_task action"""
    r = _request("post", data={ACTION_CHECKBOX_NAME: [model_instance.pk]})

    queue_action = QueueCeleryAction(task=celery_task, condition=lambda _: False)
    queue_action(admin, r, AdminActionsTestModel.objects.filter(pk=model_instance.pk))

    # Every record was rejected, task should never be delayed
    mocked_task.assert_not_called()
